Updated evergreen.yml to include the spawn host and created the script to install the automation agent

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -11,6 +11,7 @@ ignore:
 variables:
   - &go_options
     GO111MODULE: "on"
+    spawn_host_list_file: hosts.json
 functions:
   "clone":
     - command: git.get_project
@@ -77,6 +78,78 @@ functions:
           MCLI_SERVICE: ${cloud_manager_service}
           <<: *go_options
         command: make e2e-test-cloud
+  # Check SSH availability
+  ssh-ready:
+    command: shell.exec
+    params:
+      script: |
+        user=root
+        hostname=$(tr -d '"[]{}' < ${spawn_host_list_file} | cut -d , -f 1 | awk -F : '{print $2}')
+        identity_file=~/.ssh/mcipacker.pem
+
+        attempts=0
+        connection_attempts=${connection_attempts|25}
+
+        # Check for remote connectivity
+        while ! ssh \
+          -i "$identity_file" \
+          -o ConnectTimeout=10 \
+          -o ForwardAgent=yes \
+          -o IdentitiesOnly=yes \
+          -o StrictHostKeyChecking=no \
+          "$(printf "%s@%s" "$user" "$hostname")" \
+          exit 2> /dev/null
+        do
+          [ "$attempts" -ge "$connection_attempts" ] && exit 1
+          ((attempts++))
+          printf "SSH connection attempt %d/%d failed. Retrying...\n" "$attempts" "$connection_attempts"
+          # sleep for Permission denied (publickey) errors
+          sleep 10
+        done
+      shell: bash
+  "install automation agent":
+    - command: shell.exec
+      type: setup
+      params:
+        script: |
+          set -ex
+
+          while getopts 'i:h:t:u:' opt; do
+              case $opt in
+                  i) keyfile="$OPTARG";;      # SSH identity file
+                  u) user="$OPTARG";;         # Username on the remote host
+                  h) hostsfile="$OPTARG";;    # Output of Evergreen host.list
+                  *) exit 1;;
+              esac
+          done
+
+          hosts=$(cat << EOF | python - ${spawn_host_list_file}"
+          import sys
+          import json
+          with open(sys.argv[1]) as hostsfile:
+              hosts = json.load(hostsfile)
+              for host in hosts:
+                  print(host["dns_name"])
+          EOF
+          )
+          for host in $hosts; do
+              set +e
+              echo "installing the automation agent on $host"
+              ssh -i "$keyfile" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt "$user@$host" \  < scripts/automation_agent.sh
+              set -e
+          done
+  "deploy spawn host":
+    - command: host.create
+      params:
+        provider: ec2
+        distro: rhel70-small
+        num_hosts: 1
+    - command: host.list
+      params:
+        wait: true
+        timeout_seconds: 300
+        num_hosts: 1
+        path: ${spawn_host_list_file}
   "lint":
     - command: subprocess.exec
       type: test
@@ -335,9 +408,27 @@ tasks:
       - func: "atlas e2e"
   - name: cloud_manager_e2e
     commands:
+      - func: "deploy spawn host"
+      - func: ssh-ready
+      - func: "install automation agent"
       - func: "clone"
       - func: "build"
       - func: "cloud manager e2e"
+  - name: deploy_spawn_host
+    commands:
+      - command: host.create
+        params:
+          provider: ec2
+          distro: rhel70-small
+          num_hosts: 1
+      - command: host.list
+        params:
+          wait: true
+          timeout_seconds: 300
+          num_hosts: 1
+          path: ${spawn_host_list_file}
+      - func: ssh-ready
+      - func: "install automation agent"
   - name: package_msi
     tags: ["packaging"]
     depends_on:
