chore: merge from master (#4131)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Wesley Nabo <102980553+Waybo26@users.noreply.github.com>
Co-authored-by: Filipe Constantinov Menezes <filipe.menezes@mongodb.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: apix-bot[bot] <168195273+apix-bot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -50,6 +50,7 @@ jobs:
           go install github.com/mattn/goveralls@v0.0.12
       - run: make unit-test
       - name: Send coverage
+        if: matrix.os == 'ubuntu-latest'
         env:
           COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         run: goveralls -parallel -coverprofile="$COVERAGE" -ignore=test/* -service=github
@@ -316,8 +317,6 @@ jobs:
           config: ${{ vars.PERMISSIONS_CONFIG }}
       - name: Checkout repository
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
       - name: Install Go
         uses: actions/setup-go@v5
         with:
@@ -327,11 +326,18 @@ jobs:
           go install github.com/mattn/goveralls@v0.0.12
       - name: set Apix Bot token
         id: app-token
-        uses: mongodb/apix-action/token@3024080388613583e3bd119bfb1ab4b4dbf43c42
+        uses: mongodb/apix-action/token@222db38e5893a57f26bd156999713aa98a55b92c
         with:
           app-id: ${{ secrets.APIXBOT_APP_ID }}
           private-key: ${{ secrets.APIXBOT_APP_PEM }}
-      - run: make e2e-test-snapshots
+      - run: |
+          set +e
+          make e2e-test-snapshots
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "::error::Snapshot tests failed, consider adding label 'update-snapshots' to re-generate them"
+          fi
+          exit $EXIT_CODE
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           TEST_CMD: gotestsum --junitfile e2e-tests.xml --format standard-verbose --
