fix: display test snapshot error message

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -317,8 +317,6 @@ jobs:
           config: ${{ vars.PERMISSIONS_CONFIG }}
       - name: Checkout repository
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
       - name: Install Go
         uses: actions/setup-go@v5
         with:
@@ -332,7 +330,14 @@ jobs:
         with:
           app-id: ${{ secrets.APIXBOT_APP_ID }}
           private-key: ${{ secrets.APIXBOT_APP_PEM }}
-      - run: make e2e-test-snapshots
+      - run: |
+          set +e
+          make e2e-test-snapshots
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "::error::Snapshot tests failed, consider adding label 'update-snapshots' to re-generate them"
+          fi
+          exit $EXIT_CODE
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           TEST_CMD: gotestsum --junitfile e2e-tests.xml --format standard-verbose --
