updated readme and added verify steps

diff --git a/.github/workflows/docker-release.yml b/.github/workflows/docker-release.yml
--- a/.github/workflows/docker-release.yml
+++ b/.github/workflows/docker-release.yml
@@ -13,7 +13,7 @@ jobs:
       PLATFORMS: linux/amd64,linux/arm64
     steps:
       - name: Check out code
-        uses: actions/checkout@v4
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
       - name: Set date
         id: set-date
         run: |
@@ -21,7 +21,7 @@ jobs:
           echo DATE=${DATE} >> $GITHUB_ENV
       - name: 'Get latest tag'
         id: get-latest-tag
-        uses: oprypin/find-latest-tag@v1
+        uses: oprypin/find-latest-tag@e1e0e606cc7e9ede25140a5a139b3a5a1b717ece
         with:
           repository: mongodb/mongodb-atlas-cli
           releases-only: true
@@ -31,14 +31,14 @@ jobs:
           release_tag=${{ steps.get-latest-tag.outputs.tag }}
           echo "LATEST_VERSION=${release_tag#*/}" >> $GITHUB_ENV
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
       - name: Login to Docker Hub
-        uses: docker/login-action@v3
+        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
         with:
           username: "${{ secrets.DOCKERHUB_USER }}"
           password: "${{ secrets.DOCKERHUB_SECRET }}"
       - name: Build and push image to dockerhub staging registry
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
         with:
           context: .
           platforms: ${{ env.PLATFORMS }}
@@ -65,7 +65,7 @@ jobs:
           echo DATE=${DATE} >> $GITHUB_ENV
       - name: 'Get latest tag'
         id: get-latest-tag
-        uses: oprypin/find-latest-tag@v1
+        uses: oprypin/find-latest-tag@e1e0e606cc7e9ede25140a5a139b3a5a1b717ece
         with:
           repository: mongodb/mongodb-atlas-cli
           releases-only: true
@@ -75,7 +75,7 @@ jobs:
           release_tag=${{ steps.get-latest-tag.outputs.tag }}
           echo "LATEST_VERSION=${release_tag#*/}" >> $GITHUB_ENV
       - name: Enable containerd image store # See https://github.com/docker/setup-buildx-action/issues/257#issuecomment-1722284952
-        uses: crazy-max/ghaction-setup-docker@v2
+        uses: crazy-max/ghaction-setup-docker@d9be6cade441568ba10037bce5221b8f564981f1
         with:
           version: v24.0.6
           daemon-config: |
@@ -132,6 +132,12 @@ jobs:
             --tag ${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }} \
             --tag ${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }}-${{ env.DATE }} \
             ${{ env.STAGING_IMAGE_REPOSITORY }}:latest
+      - name: Login to Quay
+        uses: docker/login-action@v3
+        with:
+          registry: "${{ env.QUAY }}"
+          username: "${{ secrets.QUAY_USER }}"
+          password: "${{ secrets.QUAY_TOKEN }}"
       - name: Push image to Quay public registry
         run: |
           docker buildx imagetools create \
@@ -139,3 +145,73 @@ jobs:
             --tag ${{ env.QUAY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }} \
             --tag ${{ env.QUAY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }}-${{ env.DATE }} \
             ${{ env.IMAGE_REPOSITORY }}:latest
+  verify_docker_image:
+    name: Verify Docker Image
+    needs: [ publish_images ]
+    runs-on: ubuntu-latest
+    env:
+      IMAGE_REPOSITORY: mongodb/atlas
+    steps:
+      - name: Login to Docker Hub
+        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
+        with:
+          username: "${{ secrets.DOCKERHUB_USER }}"
+          password: "${{ secrets.DOCKERHUB_SECRET }}"
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4
+        with:
+          cosign-release: 'v2.2.3'
+      - name: Verify Docker Image
+        env:
+          IMAGE: ${{ env.IMAGE_REPOSITORY }}:latest
+        run: |
+          # Download MongoDB Atlas CLI Public Key
+          curl https://cosign.mongodb.com/atlas-cli.pem > atlas-cli.pem
+          
+          # Download Docker Image
+          docker pull "${IMAGE}"
+          
+          # Verify the signature
+          COSIGN_REPOSITORY=docker.io/mongodb/signatures cosign verify --private-infrastructure --key=./atlas-cli.pem "docker.io/${IMAGE}"
+          
+          # Check the exit status of cosign verify
+          if [ $? -ne 0 ]; then
+            echo "Error: Signature verification for ${IMAGE} failed."
+            exit 1
+          fi
+  verify_quay_image:
+    name: Verify Quay Image
+    needs: [ publish_images ]
+    runs-on: ubuntu-latest
+    env:
+      IMAGE_REPOSITORY: mongodb/atlas
+      QUAY: quay.io
+    steps:
+      - name: Login to Quay
+        uses: docker/login-action@v3
+        with:
+          registry: "${{ env.QUAY }}"
+          username: "${{ secrets.QUAY_USER }}"
+          password: "${{ secrets.QUAY_TOKEN }}"
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4
+        with:
+          cosign-release: 'v2.2.3'
+      - name: Verify Quay Image
+        env:
+          IMAGE: ${{ env.QUAY }}/${{ env.IMAGE_REPOSITORY }}:latest
+        run: |
+          # Download MongoDB Atlas CLI Public Key
+          curl https://cosign.mongodb.com/atlas-cli.pem > atlas-cli.pem
+          
+          # Download Quay Image
+          docker pull "${IMAGE}"
+          
+          # Verify the signature
+          COSIGN_REPOSITORY=docker.io/mongodb/signatures cosign verify --private-infrastructure --key=./atlas-cli.pem "${IMAGE}"
+          
+          # Check the exit status of cosign verify
+          if [ $? -ne 0 ]; then
+            echo "Error: Signature verification for ${IMAGE} failed."
+            exit 1
+          fi
